config/routes.rb
Rails.application.routes.draw do
  resources :votes
  resources :topic_logs
  resources :topics do
      member do
        post 'upvote'
      end
    end
  resources :people

  root 'topics#index'
  get ":", to: "topc#edit", as: :edit
  # The priority is based upon order of reation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/topic_log.rb
class TopicLog < ActiveRecord::Base
  belongs_to :person
  belongs_to :topic
end

app/controllers/topic_logs_controller.rb
class TopicLogsController < ApplicationController
  before_action :set_topic_log, only: [:show, :edit, :update, :destroy]

  # GET /topic_logs
  # GET /topic_logs.json
  def index
    @topic_logs = TopicLog.all
  end

  # GET /topic_logs/1
  # GET /topic_logs/1.json
  def show
  end

  # GET /topic_logs/new
  def new
    @topic_log = TopicLog.new
  end

  # GET /topic_logs/1/edit
  def edit
  end

  # POST /topic_logs
  # POST /topic_logs.json
  def create
    @topic_log = TopicLog.new(topic_log_params)

    respond_to do |format|
      if @topic_log.save
        format.html { redirect_to @topic_log, notice: 'Topic log was successfully created.' }
        format.json { render :show, status: :created, location: @topic_log }
      else
        format.html { render :new }
        format.json { render json: @topic_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topic_logs/1
  # PATCH/PUT /topic_logs/1.json
  def update
    respond_to do |format|
      if @topic_log.update(topic_log_params)
        format.html { redirect_to @topic_log, notice: 'Topic log was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic_log }
      else
        format.html { render :edit }
        format.json { render json: @topic_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topic_logs/1
  # DELETE /topic_logs/1.json
  def destroy
    @topic_log.destroy
    respond_to do |format|
      format.html { redirect_to topic_logs_url, notice: 'Topic log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic_log
      @topic_log = TopicLog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_log_params
      params.require(:topic_log).permit(:person_id, :topic_id, :posted)
    end
end

app/helpers/topic_logs_helper.rb
module TopicLogsHelper
end

app/views/topic_logs/_form.html.erb
<center><%= form_for(@topic_log) do |f| %>
  <% if @topic_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic_log.errors.count, "error") %> prohibited this topic_log from being saved:</h2>

      <ul>
      <% @topic_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :person_id %><br>
    <%= f.text_field :person_id %>
  </div>
  <div class="field">
    <%= f.label :topic_id %><br>
    <%= f.text_field :topic_id %>
  </div>
  <div class="field">
    <%= f.label :posted %><br>
    <%= f.date_select :posted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  </center>
<% end %>

app/views/topic_logs/edit.html.erb
<h1>Editing Topic Log</h1>

<%= render 'form' %>

<%= button_to 'Show', @topic_log, :method => "get" %> 
<%= button_to 'Back', topic_logs_path, :method => "get" %>

app/views/topic_logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Topic Logs</h1>

<table>
  <thead>
    <tr>
      <th>Person</th>
      <th>Topic</th>
      <th>Posted</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
  <tr>
    <td><%= topic.title %></td>
    <td><%= topic.description %></td>
    <td><%= pluralize(topic.votes.count, "vote") %></td>
    <td><%= button_to '+1', upvote_topic_path(topic), method: :post %></td>
    <td><%= button_to 'Show', topic, :method => "get" %></td>
    <td><%= button_to 'Edit', edit_topic_path(topic), :method => "get" %></td>
    <td><%= button_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
    <% end %>
  </tbody>
</table>

<br>

<%=button_to 'New Topic log', new_topic_log_path, :method => "get" %>

app/views/topic_logs/new.html.erb
<h1>New Topic Log</h1>

<%= render 'form' %>

<%= button_to 'Back', topic_logs_path, :method => "get" %>

app/views/topic_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Person:</strong>
  <%= @topic_log.person %>
</p>

<p>
  <strong>Topic:</strong>
  <%= @topic_log.topic %>
</p>

<p>
  <strong>Posted:</strong>
  <%= @topic_log.posted %>
</p>

<table>
	<td><%= button_to 'Edit', edit_topic_log_path(@topic_log), :method => "get" %> </td>
	<td><%= button_to 'Back', topic_logs_path, :method => "get" %></td>
</table>